version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/apps/site"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      npm-minor-patch:
        update-types:
          - "minor"
          - "patch"
      npm-major:
        update-types:
          - "major"
    open-pull-requests-limit: 5
