name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependdency-path: .pnpm-lock.yaml
      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.4
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint & typecheck
        run: pnpm --filter site astro check
      - name: Build
        run: pnpm --filter site build
